core/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    
    path('', dashboard, name='dashboard'), 
    path('login', login, name='login'), 
    path('logout', logout_user, name='logout'), 

    path('departments/', departments, name='departments'),
    path('department/create/', department_create, name='department_create'),
    path('department/<slug:slug>/edit/', department_update, name='department_update'),
    path('department/<slug:slug>/delete/', department_delete, name='department_delete'),
    
    path('jobs/', JobListView.as_view(), name='job-list'),
    path('job/create/', JobCreateView.as_view(), name='job-create'),
    path('job/<slug:slug>/update/', JobUpdateView.as_view(), name='job-update'),
    path('job/<slug:slug>/delete/', job_delete, name='job-delete'),

    path('applications/', ApplicationListView.as_view(), name='application-list'),
    path('applications/<slug:slug>', view_application, name='view_application'),

    path('acccont/application/department/<slug:slug>', view_application_job, name='view_application_job'),
   
    path('resumes/', ResumeListView.as_view(), name='resume-list'),
    path('resumes/<slug:slug>', view_resume, name='view_resume'),

    path('messages/', MessageListView.as_view(), name='message-list'),
    path('message/<slug:slug>', view_message, name='view_message'),


    # path('applications/create/', ApplicationCreateView.as_view(), name='application-create'),
    # path('applications/<slug:slug>/update/', ApplicationUpdateView.as_view(), name='application-update'),
    # path('applications/<slug:slug>/delete/', ApplicationDeleteView.as_view(), name='application-delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('core.urls')),
    path('', include('website.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.core.exceptions import ValidationError
import os



def validate_pdf(value):
    ext = os.path.splitext(value.name)[1]  # [0] returns path+filename
    valid_extensions = ['.pdf']
    if not ext.lower() in valid_extensions:
        raise ValidationError('Unsupported file extension. Only PDF files are allowed.')



# Create your models here.
class Department(models.Model):

    STATUS_CHOICES = [
        ('active', 'Active'),
        ('inactive', 'Inactive'),
    ]


    name = models.CharField(max_length=100)
    icon = models.CharField(max_length=60)
    created_at = models.DateTimeField(auto_now_add=True)
    openings = models.IntegerField()
    slug = models.SlugField(unique=True, blank=True)
    status = models.CharField(max_length=8, choices=STATUS_CHOICES, default='active')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
            original_slug = self.slug
            counter = 1
            while Department.objects.filter(slug=self.slug).exists():
                self.slug = f"{original_slug}-{counter}"
                counter += 1
        super(Department, self).save(*args, **kwargs)

    def __str__(self):
        return self.name




class Job(models.Model):


    JOB_TYPE_CHOICES = [
        ('Full Time', 'Full Time'),
        ('Part Time', 'Part Time'),
        ('Internship', 'Internship'),
        ('Freelance', 'Freelance'),
    ]

    EXPERIENCE_CHOICES = [
        ('0-1', '0-1 years'),
        ('1-2', '1-2 years'),
        ('2-3', '2-3 years'),
        ('3-4', '3-4 years'),
        ('4-5', '4-5 years'),
        ('5+', '5+ years'),
    ]


    STATUS_CHOICES = [
        ('active', 'Active'),
        ('inactive', 'Inactive'),
    ]

    title = models.CharField(max_length=255)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    location = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    salary = models.CharField(max_length=255)
    job_type = models.CharField(max_length=15, choices=JOB_TYPE_CHOICES, default='full time')
    experience = models.CharField(max_length=3, choices=EXPERIENCE_CHOICES)
    job_description = models.TextField()
    skills_required = RichTextField()
    slug = models.SlugField(unique=True, blank=True)
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default='active')


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            original_slug = self.slug
            counter = 1
            while Job.objects.filter(slug=self.slug).exists():
                self.slug = f"{original_slug}-{counter}"
                counter += 1
        super(Job, self).save(*args, **kwargs)


    def __str__(self):
        return self.title


    
class Application(models.Model):
    EXPERIENCE_CHOICES = [
        ('0-1', '0-1 years'),
        ('1-2', '1-2 years'),
        ('2-3', '2-3 years'),
        ('3-4', '3-4 years'),
        ('4-5', '4-5 years'),
        ('5+', '5+ years'),
    ]

    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    mobile_number = models.CharField(max_length=15)
    experience = models.CharField(max_length=3, choices=EXPERIENCE_CHOICES)
    skills = RichTextField()
    resume = models.FileField(upload_to='resumes/', validators=[validate_pdf])
    slug = models.SlugField(unique=True, blank=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
            original_slug = self.slug
            counter = 1
            while Application.objects.filter(slug=self.slug).exists():
                self.slug = f"{original_slug}-{counter}"
                counter += 1
        super(Application, self).save(*args, **kwargs)



    def __str__(self):
        return f'{self.name} - {self.job.title}'




class Resume(models.Model):

    EXPERIENCE_CHOICES = [
        ('0-1', '0-1 years'),
        ('1-2', '1-2 years'),
        ('2-3', '2-3 years'),
        ('3-4', '3-4 years'),
        ('4-5', '4-5 years'),
        ('5+', '5+ years'),
    ]
    
    
    name = models.CharField(max_length=255)
    email = models.EmailField()
    number = models.CharField(max_length=14)
    experience = models.CharField(max_length=3, choices=EXPERIENCE_CHOICES)
    skills = RichTextField()
    resume = models.FileField(upload_to='resumes/', validators=[validate_pdf])
    job_title = models.CharField(max_length=255)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=255, unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name + '-' + self.job_title)
            original_slug = self.slug
            counter = 1
            while Resume.objects.filter(slug=self.slug).exists():
                self.slug = f"{original_slug}-{counter}"
                counter += 1
        super(Resume, self).save(*args, **kwargs)




    def __str__(self):
        return self.name




class Message(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    number = models.CharField(max_length=20)
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name + '-' + self.subject)
            original_slug = self.slug
            counter = 1
            while Message.objects.filter(slug=self.slug).exists():
                self.slug = f"{original_slug}-{counter}"
                counter += 1
        super(Message, self).save(*args, **kwargs)



    def __str__(self):
        return f"{self.name} - {self.subject}"

templates/backend/application-view.html
{% extends 'backend/base.html' %}
{% load static %}

{% block title %}Application Details | Dashboard{% endblock %}


{% block head %}
<style>
    .input_div {
        margin-bottom: 1rem;
    }
    .form-control {
        border: 1px solid #ced4da;
        border-radius: .25rem;
        padding: 15px;
        word-wrap: break-word;
    }
</style>
{% endblock head %}
    

{% block content %}
<div class="row mb-32 gy-32">
    <div class="col-12">
        <div class="row align-items-center justify-content-between g-24">
            <div class="col-12 col-md-6">
                <h3>Application Details</h3>
                <p class="hp-p1-body mb-0">Here you can view the details of the application</p>
            </div>
        </div>
    </div>

    <div class="col-12">
        <div class="row g-32">
            <div class="col-12 col-lg-12">
                <div class="row g-32">
                    <div class="col-12">
                        <div class="card hp-project-ecommerce-table-card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12">
                                        <div class="d-flex align-items-center justify-content-between mb-32">
                                            <h5 class="mb-0">Application Details</h5>
                                        </div>

                                        <form method="post" action="#" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-md-6 input_div">
                                                    <label for="id_job">Job</label>
                                                    <input type="text" value="{{ application.job.title }}" readonly class="form-control">
                                                </div>
                                                <div class="col-md-6 input_div">
                                                    <label for="id_department">Department</label>
                                                    <input type="text" value="{{ application.department.name }}" readonly class="form-control">
                                                </div>
                                                <div class="col-md-6 input_div">
                                                    <label for="id_name">Name</label>
                                                    <input type="text" value="{{ application.name }}" readonly class="form-control">
                                                </div>
                                                <div class="col-md-6 input_div">
                                                    <label for="id_email">Email</label>
                                                    <input type="email" value="{{ application.email }}" readonly class="form-control">
                                                </div>
                                                <div class="col-md-6 input_div">
                                                    <label for="id_mobile_number">Mobile Number</label>
                                                    <input type="text" value="{{ application.mobile_number }}" readonly class="form-control">
                                                </div>
                                                <div class="col-md-6 input_div">
                                                    <label for="id_experience">Experience</label>
                                                    <input type="text" value="{{ application.get_experience_display }}" readonly class="form-control">
                                                </div>
                                                <div class="col-md-12 input_div">
                                                    <label for="id_skills">Skills</label>
                                                    <div id="id_skills" class="form-control" >{{ application.skills|safe }}</div>
                                                </div>
                                                <div class="col-md-12 input_div d-flex justify-content-start align-items-center">
                                                    <label for="id_resume">Resume</label>
                                                    <a href="{{ application.resume.url }}" target="_blank" class="btn btn_resume">View Resume</a>
                                                </div>
                                            </div>

                                            <div class="sub_btn d-none">
                                                <button type="submit">Submit</button>
                                            </div>
                                        </form>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    document.querySelector('.applications').classList.add('active');

    function updateIcon() {
        var iconInput = document.getElementById('id_icon');
        var iconPreview = document.getElementById('iconPreview');
        iconPreview.className = 'icon_ ' + iconInput.value;
    }

    document.getElementById('id_icon').addEventListener('input', updateIcon);
    // Initial call to set the icon if there's a pre-filled value
    updateIcon();
</script>
{% endblock script %}

templates/backend/department_form.html
{% extends 'backend/base.html' %}
{% load static %}

{% block title %}Department | Dashboard{% endblock %}

{% block content %}


<div class="row mb-32 gy-32">
    <div class="col-12">
        <div class="row align-items-center justify-content-between g-24">
            <div class="col-12 col-md-6">
                <h3>Create Departments </h3>
                <p class="hp-p1-body mb-0">Here you can create new department</p>
            </div>
        </div>
    </div>

    <div class="col-12">

        <div class="row g-32">
            <div class="col-12 col-lg-12">
                <div class="row g-32">
                    <div class="col-12">
                        <div class="card hp-project-ecommerce-table-card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12">
                                        <div class="d-flex align-items-center justify-content-between mb-32">
                                            <h5 class="mb-0">{% if form.instance.pk %}Update Department{% else %}Create New Department{% endif %}</h5>
                                        </div>

                                        <form  method="post" enctype="multipart/form-data" action="">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-md-6 input_div">
                                                    <label for="id_name">Department Name</label>
                                                    {{ form.name }}
                                                </div>
                                                <div class="col-md-6 input_div">
                                                    <label for="id_openings">How many openings available</label>
                                                    {{ form.openings }}
                                                </div>
                                                <div class="col-md-6 input_div">
                                                    <label for="id_icon">Icon</label>
                                                    {{ form.icon }}
                                                    <span class="icon_" id="iconPreview"></span>
                                                </div>
                                            </div>
                                    
                                            <ul class="radio-switch">
                                                <li class="radio-switch__item">
                                                    <input class="radio-switch__input ri5-sr-only" type="radio" name="status" id="radio-1" value="active" checked {% if form.initial.status == "active" %}checked{% endif %}>
                                                    <label class="radio-switch__label" for="radio-1">Active</label>
                                                </li>
                                                <li class="radio-switch__item">
                                                    <input class="radio-switch__input ri5-sr-only" type="radio" name="status" id="radio-2" value="inactive" {% if form.initial.status == "inactive" %}checked{% endif %}>
                                                    <label class="radio-switch__label" for="radio-2">Inactive</label>
                                                    <div aria-hidden="true" class="radio-switch__marker"></div>
                                                </li>
                                            </ul>
                                    
                                            <div class="sub_btn">
                                                <button type="submit">Submit</button>
                                            </div>
                                        </form>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}



{% block script %}
    <script>
        document.querySelector('.department').classList.add('active')
    </script>
    <script>
        function updateIcon() {
            var iconInput = document.getElementById('id_icon');
            var iconPreview = document.getElementById('iconPreview');
            iconPreview.className = 'icon_ ' + iconInput.value;
        }

        document.getElementById('id_icon').addEventListener('input', updateIcon);
        // Initial call to set the icon if there's a pre-filled value
        updateIcon();
    </script>
{% endblock script %}
    

templates/backend/job-form.html
{% extends 'backend/base.html' %}
{% load static %}

{% block title %}Job | Dashboard{% endblock %}

{% block content %}

<div class="row mb-32 gy-32">
    <div class="col-12">
        <div class="row align-items-center justify-content-between g-24">
            <div class="col-12 col-md-6">
                <h3>{% if form.instance.pk %}Update Job{% else %}Create Job{% endif %}</h3>
                <p class="hp-p1-body mb-0">Here you can {% if form.instance.pk %}update an existing{% else %}create a new{% endif %} job</p>
            </div>
        </div>
    </div>

    <div class="col-12">
        <div class="row g-32">
            <div class="col-12 col-lg-12">
                <div class="row g-32">
                    <div class="col-12">
                        <div class="card hp-project-ecommerce-table-card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12">
                                        <div class="d-flex align-items-center justify-content-between mb-32">
                                            <h5 class="mb-0">{% if form.instance.pk %}Update Job{% else %}Create New Job{% endif %}</h5>
                                        </div>

                                        <form method="post" enctype="multipart/form-data" action="">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-md-6 input_div">
                                                    <label for="id_title">Job Title</label>
                                                    {{ form.title }}
                                                </div>
                                                <div class="col-md-6 input_div">
                                                    <label for="id_department">Department</label>
                                                    {{ form.department }}
                                                </div>
                                                <div class="col-md-6 input_div">
                                                    <label for="id_location">Location</label>
                                                    {{ form.location }}
                                                </div>
                                                <div class="col-md-6 input_div">
                                                    <label for="id_salary">Salary</label>
                                                    {{ form.salary }}
                                                </div>
                                                <div class="col-md-6 input_div">
                                                    <label for="id_job_type">Job Type</label>
                                                    {{ form.job_type }}
                                                </div>
                                                <div class="col-md-6 input_div">
                                                    <label for="id_experience">Experience</label>
                                                    {{ form.experience }}
                                                </div>
                                                <div class="col-md-12 input_div">
                                                    <label for="id_job_description">Job Description</label>
                                                    {{ form.job_description }}
                                                </div>
                                                <div class="col-md-12 input_div">
                                                    <label for="id_skills_required">Skills Required</label>
                                                    {{ form.skills_required }}
                                                </div>
                                            </div>
                                    
                                            <ul class="radio-switch">
                                                <li class="radio-switch__item">
                                                    <input checked class="radio-switch__input ri5-sr-only" type="radio" name="status" id="radio-1" value="active" {% if form.initial.status == "active" %}checked{% endif %}>
                                                    <label class="radio-switch__label" for="radio-1">Active</label>
                                                </li>
                                                <li class="radio-switch__item">
                                                    <input class="radio-switch__input ri5-sr-only" type="radio" name="status" id="radio-2" value="inactive" {% if form.initial.status == "inactive" %}checked{% endif %}>
                                                    <label class="radio-switch__label" for="radio-2">Inactive</label>
                                                    <div aria-hidden="true" class="radio-switch__marker"></div>
                                                </li>
                                            </ul>
                                    
                                            <div class="sub_btn">
                                                <button type="submit">Submit</button>
                                            </div>
                                        </form>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
    
    <script src="https://cdn.ckeditor.com/4.16.2/standard/ckeditor.js"></script>

    <script>
        document.querySelector('.jobs').classList.add('active')
    </script>


    <script>
        document.addEventListener("DOMContentLoaded", function() {
            var textarea = document.querySelector('textarea#id_skills_required');
            var editor = CKEDITOR.replace(textarea.id);

            editor.on('instanceReady', function() {
                // Using a slight delay to ensure the element is available
                setTimeout(function() {
                    console.log(document.querySelector('#cke_notifications_area_id_skills_required'))
                    document.querySelector('#cke_notifications_area_id_skills_required').classList.add('d-none')
                }, 100);
            });
        });
    </script>
{% endblock script %}

templates/backend/resume-view.html
{% extends 'backend/base.html' %}
{% load static %}

{% block title %}Resume Details | Dashboard{% endblock %}


{% block head %}
<style>
    .input_div {
        margin-bottom: 1rem;
    }
    .form-control {
        border: 1px solid #ced4da;
        border-radius: .25rem;
        padding: 15px;
        word-wrap: break-word;
    }
</style>
{% endblock head %}
    

{% block content %}
<div class="row mb-32 gy-32">
    <div class="col-12">
        <div class="row align-items-center justify-content-between g-24">
            <div class="col-12 col-md-6">
                <h3>Resume Details</h3>
                <p class="hp-p1-body mb-0">Here you can view the details of the resume</p>
            </div>
        </div>
    </div>

    <div class="col-12">
        <div class="row g-32">
            <div class="col-12 col-lg-12">
                <div class="row g-32">
                    <div class="col-12">
                        <div class="card hp-project-ecommerce-table-card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12">
                                        <div class="d-flex align-items-center justify-content-between mb-32">
                                            <h5 class="mb-0">Resume Details</h5>
                                        </div>

                                        <form method="post" action="#" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-md-6 input_div">
                                                    <label for="id_job">Name</label>
                                                    <input type="text" value="{{ resume.name }}" readonly class="form-control">
                                                </div>
                                                <div class="col-md-6 input_div">
                                                    <label for="id_department">Department</label>
                                                    <input type="text" value="{{ resume.department.name }}" readonly class="form-control">
                                                </div>
                                                <div class="col-md-6 input_div">
                                                    <label for="id_email">Email</label>
                                                    <input type="email" value="{{ resume.email }}" readonly class="form-control">
                                                </div>
                                                <div class="col-md-6 input_div">
                                                    <label for="id_email">Job Title</label>
                                                    <input type="email" value="{{ resume.job_title }}" readonly class="form-control">
                                                </div>
                                                <div class="col-md-6 input_div">
                                                    <label for="id_mobile_number">Mobile Number</label>
                                                    <input type="text" value="{{ resume.number }}" readonly class="form-control">
                                                </div>
                                                <div class="col-md-6 input_div">
                                                    <label for="id_experience">Experience</label>
                                                    <input type="text" value="{{ resume.get_experience_display }}" readonly class="form-control">
                                                </div>
                                                <div class="col-md-12 input_div">
                                                    <label for="id_skills">Skills</label>
                                                    <div id="id_skills" class="form-control" >{{ resume.skills|safe }}</div>
                                                </div>
                                                <div class="col-md-12 input_div d-flex justify-content-start align-items-center">
                                                    <label for="id_resume">Resume</label>
                                                    <a href="{{ resume.resume.url }}" target="_blank" class="btn btn_resume">View Resume</a>
                                                </div>
                                            </div>

                                            <div class="sub_btn d-none">
                                                <button type="submit">Submit</button>
                                            </div>
                                        </form>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    document.querySelector('.resumes').classList.add('active');
</script>
{% endblock script %}