core/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    
    path('', dashboard, name='dashboard'), 
    path('login', login, name='login'), 
    path('logout', logout_user, name='logout'), 

    path('departments/', departments, name='departments'),
    path('department/create/', department_create, name='department_create'),
    path('department/<slug:slug>/edit/', department_update, name='department_update'),
    path('department/<slug:slug>/delete/', department_delete, name='department_delete'),
    
    path('jobs/', JobListView.as_view(), name='job-list'),
    path('job/create/', JobCreateView.as_view(), name='job-create'),
    path('job/<slug:slug>/update/', JobUpdateView.as_view(), name='job-update'),
    path('job/<slug:slug>/delete/', job_delete, name='job-delete'),

    path('applications/', ApplicationListView.as_view(), name='application-list'),
    path('applications/<slug:slug>', view_application, name='view_application'),

    path('acccont/application/department/<slug:slug>', view_application_job, name='view_application_job'),
   
    path('resumes/', ResumeListView.as_view(), name='resume-list'),
    path('resumes/<slug:slug>', view_resume, name='view_resume'),

    path('messages/', MessageListView.as_view(), name='message-list'),
    path('message/<slug:slug>', view_message, name='view_message'),


    # path('applications/create/', ApplicationCreateView.as_view(), name='application-create'),
    # path('applications/<slug:slug>/update/', ApplicationUpdateView.as_view(), name='application-update'),
    # path('applications/<slug:slug>/delete/', ApplicationDeleteView.as_view(), name='application-delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('core.urls')),
    path('', include('website.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.core.exceptions import ValidationError
import os



def validate_pdf(value):
    ext = os.path.splitext(value.name)[1]  # [0] returns path+filename
    valid_extensions = ['.pdf']
    if not ext.lower() in valid_extensions:
        raise ValidationError('Unsupported file extension. Only PDF files are allowed.')



# Create your models here.
class Department(models.Model):

    STATUS_CHOICES = [
        ('active', 'Active'),
        ('inactive', 'Inactive'),
    ]


    name = models.CharField(max_length=100)
    icon = models.CharField(max_length=60)
    created_at = models.DateTimeField(auto_now_add=True)
    openings = models.IntegerField()
    slug = models.SlugField(unique=True, blank=True)
    status = models.CharField(max_length=8, choices=STATUS_CHOICES, default='active')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
            original_slug = self.slug
            counter = 1
            while Department.objects.filter(slug=self.slug).exists():
                self.slug = f"{original_slug}-{counter}"
                counter += 1
        super(Department, self).save(*args, **kwargs)

    def __str__(self):
        return self.name




class Job(models.Model):


    JOB_TYPE_CHOICES = [
        ('Full Time', 'Full Time'),
        ('Part Time', 'Part Time'),
        ('Internship', 'Internship'),
        ('Freelance', 'Freelance'),
    ]

    EXPERIENCE_CHOICES = [
        ('0-1', '0-1 years'),
        ('1-2', '1-2 years'),
        ('2-3', '2-3 years'),
        ('3-4', '3-4 years'),
        ('4-5', '4-5 years'),
        ('5+', '5+ years'),
    ]


    STATUS_CHOICES = [
        ('active', 'Active'),
        ('inactive', 'Inactive'),
    ]

    title = models.CharField(max_length=255)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    location = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    salary = models.CharField(max_length=255)
    job_type = models.CharField(max_length=15, choices=JOB_TYPE_CHOICES, default='full time')
    experience = models.CharField(max_length=3, choices=EXPERIENCE_CHOICES)
    job_description = models.TextField()
    skills_required = RichTextField()
    slug = models.SlugField(unique=True, blank=True)
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default='active')


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            original_slug = self.slug
            counter = 1
            while Job.objects.filter(slug=self.slug).exists():
                self.slug = f"{original_slug}-{counter}"
                counter += 1
        super(Job, self).save(*args, **kwargs)


    def __str__(self):
        return self.title


    
class Application(models.Model):
    EXPERIENCE_CHOICES = [
        ('0-1', '0-1 years'),
        ('1-2', '1-2 years'),
        ('2-3', '2-3 years'),
        ('3-4', '3-4 years'),
        ('4-5', '4-5 years'),
        ('5+', '5+ years'),
    ]

    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    mobile_number = models.CharField(max_length=15)
    experience = models.CharField(max_length=3, choices=EXPERIENCE_CHOICES)
    skills = RichTextField()
    resume = models.FileField(upload_to='resumes/', validators=[validate_pdf])
    slug = models.SlugField(unique=True, blank=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
            original_slug = self.slug
            counter = 1
            while Application.objects.filter(slug=self.slug).exists():
                self.slug = f"{original_slug}-{counter}"
                counter += 1
        super(Application, self).save(*args, **kwargs)



    def __str__(self):
        return f'{self.name} - {self.job.title}'




class Resume(models.Model):

    EXPERIENCE_CHOICES = [
        ('0-1', '0-1 years'),
        ('1-2', '1-2 years'),
        ('2-3', '2-3 years'),
        ('3-4', '3-4 years'),
        ('4-5', '4-5 years'),
        ('5+', '5+ years'),
    ]
    
    
    name = models.CharField(max_length=255)
    email = models.EmailField()
    number = models.CharField(max_length=14)
    experience = models.CharField(max_length=3, choices=EXPERIENCE_CHOICES)
    skills = RichTextField()
    resume = models.FileField(upload_to='resumes/', validators=[validate_pdf])
    job_title = models.CharField(max_length=255)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=255, unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name + '-' + self.job_title)
            original_slug = self.slug
            counter = 1
            while Resume.objects.filter(slug=self.slug).exists():
                self.slug = f"{original_slug}-{counter}"
                counter += 1
        super(Resume, self).save(*args, **kwargs)




    def __str__(self):
        return self.name




class Message(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    number = models.CharField(max_length=20)
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name + '-' + self.subject)
            original_slug = self.slug
            counter = 1
            while Message.objects.filter(slug=self.slug).exists():
                self.slug = f"{original_slug}-{counter}"
                counter += 1
        super(Message, self).save(*args, **kwargs)



    def __str__(self):
        return f"{self.name} - {self.subject}"

templates/frontend/about.html
{% extends 'frontend/base.html' %}
{% load static %}

{% block title %}
  About | Stafuel
{% endblock title %}
  


{% block content %}

    <!--Page Title-->
    <section class="page-title">
        <div class="auto-container">
            <div class="title-outer">
                <h1>About Us</h1>
                <ul class="page-breadcrumb">
                    <li><a href="#">Home</a></li>
                    <li>About Us</li>
                </ul>
            </div>
        </div>
    </section>
    <!--End Page Title-->

    <!-- About Section Three -->
    <section class="about-section-three">
        <div class="auto-container">

            <!-- Fun Fact Section -->
            <div class="fun-fact-section">
                <div class="row">
                    <!--Column-->
                    <div class="counter-column col-lg-4 col-md-4 col-sm-12 wow fadeInUp">
                        <div class="count-box"><span class="count-text" data-speed="3000" data-stop="5">0</span>K</div>
                        <h4 class="counter-title">5K active users</h4>
                    </div>
                    <!--Column-->
                    <div class="counter-column col-lg-4 col-md-4 col-sm-12 wow fadeInUp" data-wow-delay="400ms">
                        <div class="count-box"><span class="count-text" data-speed="3000" data-stop="500">0</span></div>
                        <h4 class="counter-title">Over 500 open job positions</h4>
                    </div>
                    <!--Column-->
                    <div class="counter-column col-lg-4 col-md-4 col-sm-12 wow fadeInUp" data-wow-delay="800ms">
                        <div class="count-box"><span class="count-text" data-speed="3000" data-stop="200">0</span></div>
                        <h4 class="counter-title">Over 200 Companies</h4>
                    </div>
                </div>
            </div>
            <!-- Fun Fact Section -->

            <div class="text-box">
                <h4>About Stafuel</h4>
                <p>Stafuel Consulting Services provides global and industry-agnostic talent acquisition services that have reinvented the sourcing/recruiting model. The industry is moving to a gig economy-- the days of hourly work are being phased out. The days of clear expectations and deliverables are being phased in.</p>
                <p>Historically, recruiting metrics begin at the outreach stage of the funnel (emails sent, response rate, interviews scheduled, etc.) Stafuel is providing true sourcing data such as talent mapping, individual platform results comparison, and specific boolean efficiency. We have created a model solely based on deliverables rather than hours to ensure you are getting what you want, every time. This offers full transparency, repeatability, and previously unavailable sourcing data.</p>
                <p>At Stafuel, our commitment to quality means two things. First, we are committed to delivering quality solutions, meeting expectations, and satisfying clients. Second, we are committed to continuously improving the processes by which we provide our solutions so that our work repeatedly hits the mark each time.</p>
                <p><span style="font-weight: 600; color: black;">Our Partnership Pledge : </span>At SCS, our team is committed to building strong, long-term relationships with our clients. We believe in working as a team to provide the best service for you. To achieve this, we spend time getting to know your business and requirements so we have a well-informed understanding of your needs, goals, and requirements. We deliver the right help and advice on demand, that inspires and creates trust, mutual respect, transparency, accountability, and a sense of operational partnership.</p>
                <p><span style="font-weight: 600; color: black;">Our Vision : </span>Our vision is to provide excellent services that fulfill the expectations of our client companies. We strive to be recognized and trusted all across the world by our clients as well as candidates.</p>
                <p><span style="font-weight: 600; color: black;">Our Mission : </span>Our mission is to deliver our clients as well as candidates an overwhelming recruitment service experience grounded on mutual conviction and professional principles with due economy.</p>
            </div>
        </div>
    </section>
    <!-- End About Section Three -->

    {% include 'frontend/include/testimonial.html' %}

    <!-- Work Section -->
    <section class="work-section style-two">
        <div class="auto-container">
            <div class="sec-title text-center">
                <h2>Our Services</h2>
                <div class="text">Expert solutions for all your business and hiring needs.</div>
            </div>
            <div class="row d-flex justify-content-center">
                <!-- Work Block -->
                <div class="work-block col-lg-4 col-md-6 col-sm-12">
                    <div class="inner-box">
                        <figure class="image"><img src="{% static 'frontend/images/resource/work-1.png' %}" alt=""></figure>
                        <h5>Contract Staffing</h5>
                        <p>Whether you need to fill one high-impact position or build a full project team, we're here to handle all the details from start to finish so you have the exact talent you need to achieve your business goals.</p>
                    </div>
                </div>
                <!-- Work Block -->
                <div class="work-block col-lg-4 col-md-6 col-sm-12">
                    <div class="inner-box">
                        <figure class="image"><img src="{% static 'frontend/images/resource/work-2.png' %}" alt=""></figure>
                        <h5>Managed Services</h5>
                        <p>No matter your specific IT or Technologies needs, our consultants are here to act as a true extension of your internal teams to usher your projects through from concept to implementation. We provide a flexible delivery model and scope management by utilizing a team based staffing model.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End Work Section -->
{% endblock content %}
  



{% block script %}
    <script>
        document.querySelector('.about__nav').classList.add('current')
    </script>
{% endblock script %}
    

templates/frontend/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">


<head>
  <meta charset="utf-8">
  <title>
  {% block title %}
    
  {% endblock title %}
  </title>

    <!-- Stylesheets -->
    <link href="{% static 'frontend/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'frontend/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'frontend/css/responsive.css' %}" rel="stylesheet">

    <link rel="shortcut icon" href="{% static 'frontend/images/favicon.png' %}" type="image/x-icon">

    <link rel="icon" href="{% static 'frontend/images/favicon.png' %}" type="image/x-icon">

    <!-- Responsive -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

    
    {% block head %}
        
    {% endblock head %}
        
</head>

<body data-anm=".anm">

  <div class="page-wrapper">

    <!-- Preloader -->
    <div class="preloader"></div>

    <!-- Header Span -->
    <span class="header-span"></span>


    {% include 'frontend/include/navbar.html' %}
    <!--End Main Header -->

    
    
    {% block content %}
        
    {% endblock content %}
        

    {% include 'frontend/include/footer.html' %}


  </div><!-- End Page Wrapper -->


    
    {% block script %}
        
    {% endblock script %}

    
        

    <!-- Scripts -->
    <script src="{% static 'frontend/js/jquery.js' %}"></script>
    <script src="{% static 'frontend/js/popper.min.js' %}"></script>
    <script src="{% static 'frontend/js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'frontend/js/chosen.min.js' %}"></script>
    <script src="{% static 'frontend/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'frontend/js/jquery.fancybox.js' %}"></script>
    <script src="{% static 'frontend/js/jquery.modal.min.js' %}"></script>
    <script src="{% static 'frontend/js/mmenu.polyfills.js' %}"></script>
    <script src="{% static 'frontend/js/mmenu.js' %}"></script>
    <script src="{% static 'frontend/js/appear.js' %}"></script>
    <script src="{% static 'frontend/js/anm.min.js' %}"></script>
    <script src="{% static 'frontend/js/ScrollMagic.min.js' %}"></script>
    <script src="{% static 'frontend/js/rellax.min.js' %}"></script>
    <script src="{% static 'frontend/js/owl.js' %}"></script>
    <script src="{% static 'frontend/js/wow.js' %}"></script>
    <script src="{% static 'frontend/js/script.js' %}"></script>
    


    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
        document.addEventListener("DOMContentLoaded", function() {
            {% if messages %}
                {% for message in messages %}
                    Swal.fire({
                        title: "{{ message.tags|capfirst }}",
                        text: "{{ message }}",
                        icon: "{{ message.tags }}",
                        confirmButtonText: "OK"
                    });
                {% endfor %}
            {% endif %}
        });
    </script>

    
</body>


</html>

templates/frontend/jobs.html
{% extends 'frontend/base.html' %}
{% load static %}

{% block title %}
  Jobs | Stafuel
{% endblock title %}

{% block head %}
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
{% endblock head %}
    
{% block content %}
  
    <!--Page Title-->
    <section class="page-title style-two">
        <div class="auto-container">
            <!-- Job Search Form -->
            <div class="job-search-form">
                <form id="job-filter-form" method="get" action="#">
                    <div class="row">
                        <!-- Form Group -->
                        <div class="form-group col-lg-4 col-md-12 col-sm-12">
                            <span class="icon flaticon-search-1"></span>
                            <input type="text" name="q" placeholder="Job title, keywords, or company" value="{{ query }}">
                        </div>
                        <!-- Form Group -->
                        <div class="form-group col-lg-3 col-md-12 col-sm-12 location">
                            <span class="icon flaticon-map-locator"></span>
                            <input type="text" name="location" placeholder="City or postcode" value="{{ location }}">
                        </div>
                        <!-- Form Group -->
                        <div class="form-group col-lg-3 col-md-12 col-sm-12 location">
                            <span class="icon flaticon-briefcase"></span>
                            <select class="chosen-select" name="department">
                                <option value="">All Departments</option>
                                {% for department in departments %}
                                    <option value="{{ department.id }}" {% if department_id == department.id|stringformat:"s" %}selected{% endif %}>{{ department.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <!-- Form Group -->
                        <div class="form-group col-lg-2 col-md-12 col-sm-12 text-right">
                            <button type="submit" class="theme-btn btn-style-one">Find Jobs</button>
                        </div>
                    </div>
                </form>
            </div>
            <!-- Job Search Form -->
        </div>
    </section>
    <!--End Page Title-->

    <!-- Listing Section -->
    <section class="ls-section">
        <div class="auto-container">
            <div class="filters-backdrop"></div>
            <div class="row">
                <!-- Filters Column -->
                <div class="filters-column col-lg-4 col-md-12 col-sm-12">
                    <div class="inner-column">
                        <div class="filters-outer">
                            <button type="button" class="theme-btn close-filters">X</button>
                            <!-- Switchbox Outer -->
                            <div class="switchbox-outer">
                                <h4>Job type</h4>
                                <ul class="switchbox">
                                    <li>
                                        <label class="switch">
                                            <input type="radio" name="job_type" class="job_type" value="Freelance" {% if job_type == 'Freelance' %}checked{% endif %}>
                                            <span class="slider round"></span>
                                            <span class="title">Freelance</span>
                                        </label>
                                    </li>
                                    <li>
                                        <label class="switch">
                                            <input type="radio" name="job_type" class="job_type" value="Full Time" {% if job_type == 'Full Time' %}checked{% endif %}>
                                            <span class="slider round"></span>
                                            <span class="title">Full Time</span>
                                        </label>
                                    </li>
                                    <li>
                                        <label class="switch">
                                            <input type="radio" name="job_type" class="job_type" value="Internship" {% if job_type == 'Internship' %}checked{% endif %}>
                                            <span class="slider round"></span>
                                            <span class="title">Internship</span>
                                        </label>
                                    </li>
                                    <li>
                                        <label class="switch">
                                            <input type="radio" name="job_type" class="job_type" value="Part Time" {% if job_type == 'Part Time' %}checked{% endif %}>
                                            <span class="slider round"></span>
                                            <span class="title">Part Time</span>
                                        </label>
                                    </li>
                                    <li>
                                        <label class="switch">
                                            <input type="radio" name="job_type" class="job_type" value="Temporary" {% if job_type == 'Temporary' %}checked{% endif %}>
                                            <span class="slider round"></span>
                                            <span class="title">Temporary</span>
                                        </label>
                                    </li>
                                </ul>
                            </div>
                            <!-- Radio Buttons Outer -->
                            <div class="checkbox-outer">
                                <h4>Experience Level</h4>
                                <ul class="switchbox">
                                    <li>
                                        <label class="switch">
                                            <input type="radio" name="experience" value="0-1" {% if experience == '0-1' %}checked{% endif %}>
                                            <span class="slider round"></span>
                                            <span class="title">0-1 Year</span>
                                        </label>
                                    </li>
                                    <li>
                                        <label class="switch">
                                            <input type="radio" name="experience" value="1-2" {% if experience == '1-2' %}checked{% endif %}>
                                            <span class="slider round"></span>
                                            <span class="title">1-2 Years</span>
                                        </label>
                                    </li>
                                    <li>
                                        <label class="switch">
                                            <input type="radio" name="experience" value="2-3" {% if experience == '2-3' %}checked{% endif %}>
                                            <span class="slider round"></span>
                                            <span class="title">2-3 Years</span>
                                        </label>
                                    </li>
                                    <li>
                                        <label class="switch">
                                            <input type="radio" name="experience" value="3-4" {% if experience == '3-4' %}checked{% endif %}>
                                            <span class="slider round"></span>
                                            <span class="title">3-4 Years</span>
                                        </label>
                                    </li>
                                    <li>
                                        <label class="switch">
                                            <input type="radio" name="experience" value="5+" {% if experience == '5+' %}checked{% endif %}>
                                            <span class="slider round"></span>
                                            <span class="title">5+ Years</span>
                                        </label>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Content Column -->
                <div class="content-column col-lg-8 col-md-12 col-sm-12">
                    <div class="ls-outer">
                        <button type="button" class="theme-btn btn-style-two toggle-filters">Show Filters</button>
                        <!-- ls Switcher -->
                        <div class="ls-switcher">
                            <div class="showing-result">
                                <div class="text">Showing <strong id="job-count">{{ jobs.count }}</strong> of <strong>{{ jobs.count }}</strong> jobs</div>
                            </div>
                        </div>
                        <!-- Job Block -->
                        <div id="job-list">
                            {% include 'frontend/include/job_list.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--End Listing Page Section -->
{% endblock content %}

{% block script %}

    <!-- Include jQuery from CDN -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Include jQuery UI from CDN -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    
    <script>
      $(document).ready(function() {
        document.querySelector('.jobs__nav').classList.add('current');

        // Trigger updateJobs when job type or experience changes
        const jobTypeInputs = document.querySelectorAll('input[name="job_type"]');
        const experienceInputs = document.querySelectorAll('input[name="experience"]');

        jobTypeInputs.forEach(input => {
          input.addEventListener('change', function() {
            updateJobs();
          });
        });

        experienceInputs.forEach(input => {
          input.addEventListener('change', function() {
            updateJobs();
          });
        });

        function updateJobs() {
          $.ajax({
            url: "{% url 'filter_jobs' %}",
            data: {
              job_type: $('input[name="job_type"]:checked').val(),
              experience: $('input[name="experience"]:checked').val(),
              q: $('input[name="q"]').val(),
              location: $('input[name="location"]').val(),
              department: $('select[name="department"]').val()
            },
            success: function(data) {
              $('#job-list').html(data.html);
              $('#job-count').text(data.count); // Update job count
            },
            error: function(xhr, status, error) {
              console.error("AJAX request failed: " + status + ", " + error);
            }
          });
        }
      });
    </script>
{% endblock script %}